#jdbc.driver=com.mysql.cj.jdbc.Driver
#jdbc.url=jdbc:mysql://127.0.0.1:3306/scoula_db
jdbc.driver=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
jdbc.url=jdbc:log4jdbc:mysql://localhost:3306/scoula_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
jdbc.username=scoula
jdbc.password=1234
kb.executedBy=조윤상
# =====================================================================
#  KB 사이트 주소

kb.detailUrl=https://obank.kbstar.com/quics?page=C103429&cc=b104363:b104516&isNew=N&prcode=LN20001400&QSL=F


